#!/usr/bin/env groovy

/**
 * Jenkins Pipelines for testing
 */

node {

  // Constants
  final MAINTAINER_NAME = 'mnuaud'
  final BUILD_TAG = 'latest'

  // Registry
  //TODO: modify registry adress, such as test.test.io:8080
  final DOCKER_REGISTRY = 'docker-registry-default.pocapps.poc.s2-eu.capgemini.com:5000'
  final DOCKER_REGISTRY_URL = 'https://'+DOCKER_REGISTRY
  final DOCKER_REGISTRY_CREDENTIALS = 'docker_registry_cred'

  // Github Checkout
  stage ('Checkout code') {
    // clean the working directory
    //step([$class: 'WsCleanup'])

    // checkout the branch of the repository
    git branch: 'master', credentialsId: 'github_ssh', url: 'https://github.com/mnuaud/osh-test-app.git'
  }

  // Docker Build golden images
  stage ('Build & Push Docker Golden Images'){    
      // Build the common container
//        oc start-build --from-file=docker/osh-test-common
  stage('Create Docker Image') {
    dir('docker/osh-test-common') {
      docker.build("osh-test/test-common:${BUILD_TAG}")
    }
}             
//TODO        
      // Build the cache container
//TODO            
      // Build the Web frontoffice container

  }

// TODO check source code is correctly copied in the container at the good location
//  stage ('Build Web FRONT image') {
//  }
 
//TODO 
//  stage('Push Web back & front images to Registry'){
//  }
}